import React, { useState, useEffect, useRef } from 'react';
import { useHomework } from '../context/HomeworkCtx';
import { usePipeline } from '../hooks/usePipeline';
import { PipelineChip } from '../components/ai/PipelineChip';
import { AIConfigModal } from '../components/ai/AIConfigModal';

/**
 * GradeStudio: page for uploading submissions, selecting services,
 * running the grading pipeline, and viewing results.
 */
export default function GradeStudio() {
  const { state, dispatch } = useHomework();
  const [showConfig, setShowConfig] = useState(false);
  const [localFiles, setLocalFiles] = useState<FileList | null>(null);
  const resultsContainerRef = useRef<HTMLDivElement>(null);

  // Define AI micro-services with labels & descriptions
  const services = [
    { key: 'LLM_RubricForge', label: 'Rubric Forge', description: 'Generate rubric criteria from an exemplar answer. Outputs a JSON array of {name, weight}.' },
    { key: 'EssayLLMGrader', label: 'Essay Grader', description: 'Score essays 0–100 and provide bullet-point feedback on strengths and weaknesses.' },
    { key: 'CodeRunner', label: 'Code Runner', description: 'Compile and test code submissions. Returns passed/total counts plus console logs.' },
    { key: 'PlagiarismGuard', label: 'Plagiarism Guard', description: 'Check similarity against known sources. Returns match % and top source URLs.' },
    { key: 'KnowledgeTracer', label: 'Knowledge Tracer', description: 'Predict topic mastery probabilities. Outputs a mapping of topic names to scores.' },
    { key: 'StudyPlanGenerator', label: 'Study Plan', description: 'Generate personalized study tasks based on low-scoring rubric criteria.' }
  ];

  // Raw results explanations
  const rawExplanations: Record<string, string> = {
    LLM_RubricForge: 'This JSON lists the rubric criteria generated by the Rubric Forge service (name and weight).',
    EssayLLMGrader: 'This output shows the numeric score (0–100) and detailed feedback bullets for the essay.',
    CodeRunner: 'Shows how many unit tests passed out of the total and the console log messages.',
    PlagiarismGuard: 'Displays the percentage match against known sources and links to the top matches.',
    KnowledgeTracer: 'Provides predicted mastery probabilities (0–1) for each topic in the assignment.',
    StudyPlanGenerator: 'Lists actionable study plan items tailored to low-scoring criteria.'
  };

  // Run pipeline on service selection change
  usePipeline();

  // Auto-scroll to bottom on new results
  useEffect(() => {
    const container = resultsContainerRef.current;
    if (container) container.scrollTop = container.scrollHeight;
  }, [state.results]);

  // Handle file uploads
  const handleFiles = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files) {
      setLocalFiles(files);
      Array.from(files).forEach((file) =>
        dispatch({ type: 'ADD_SUBMISSION', payload: file })
      );
    }
  };

  // Toggle service selection
  const toggleService = (key: string) => {
    const selected = state.selectedServices.includes(key);
    const updated = selected
      ? state.selectedServices.filter((s) => s !== key)
      : [...state.selectedServices, key];
    dispatch({ type: 'SET_SELECTED_SERVICES', payload: updated });
  };

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold">Grade Studio</h1>
      <p className="text-gray-600">
        Upload submissions, select services, and track your AI grading pipeline in action.
      </p>

      {/* File Upload */}
      <div>
        <label className="block mb-2 font-medium">Upload Submissions</label>
        <input
          type="file"
          multiple
          onChange={handleFiles}
          className="block w-full border border-gray-300 rounded p-2"
        />
        <p className="text-gray-500 text-sm mt-1">
          Drag & drop or click to browse. Supports <code>.pdf</code>, <code>.docx</code>, <code>.txt</code>.
        </p>
      </div>

      {/* Service Selection */}
      <div>
        <h2 className="text-xl font-semibold mb-2">Select AI Services</h2>
        <p className="text-gray-500 text-sm mb-4">
          Check the services to include; uncheck to exclude. Descriptions below.
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {services.map(({ key, label, description }) => (
            <label
              key={key}
              className="flex items-start space-x-3 p-4 border rounded-lg hover:shadow-md transition max-w-md"
            >
              <input
                type="checkbox"
                checked={state.selectedServices.includes(key)}
                onChange={() => toggleService(key)}
                className="mt-1 h-5 w-5 text-accent border-gray-300 rounded focus:ring-accent"
              />
              <div className="flex-1">
                <div className="flex justify-between items-center">
                  <span className="font-medium text-sm">{label}</span>
                  {state.selectedServices.includes(key) && (
                    <span className="text-success text-xs">Selected</span>
                  )}
                </div>
                <p className="text-xs text-gray-500 mt-1 max-h-12 overflow-hidden">
                  {description}
                </p>
              </div>
            </label>
          ))}
        </div>
      </div>

      {/* Pipeline Status */}
      <div>
        <h2 className="text-xl font-semibold mb-2">Pipeline Status</h2>
        <div className="flex flex-wrap gap-2">
          {state.selectedServices.map((svc) => (
            <PipelineChip key={svc} service={svc} />
          ))}
        </div>
      </div>

      {/* Raw Results */}
      <div>
        <h2 className="text-xl font-semibold mb-2">Raw Results</h2>
        <p className="text-gray-600 text-sm mb-2">
          Below are the unprocessed responses returned by each service. Use these to drive custom feedback.
        </p>
        <div
          ref={resultsContainerRef}
          className="max-h-80 overflow-y-auto space-y-4 bg-white p-4 rounded shadow-sm"
        >
          {state.results.map(({ service, res }, idx) => (
            <div key={idx} className="p-4 bg-gray-50 rounded">
              <h3 className="font-semibold">{service}</h3>
              <p className="text-gray-600 text-xs mb-2">
                {rawExplanations[service]}
              </p>
              <pre className="text-sm whitespace-pre-wrap">{JSON.stringify(res, null, 2)}</pre>
            </div>
          ))}
        </div>
      </div>

      {/* Configure Mocks */}
      <button
        onClick={() => setShowConfig(true)}
        className="mt-4 px-4 py-2 rounded bg-info text-white hover:bg-info-dark"
      >
        Configure AI Mocks
      </button>
      <AIConfigModal isOpen={showConfig} onClose={() => setShowConfig(false)} />
    </div>
  );
}

